<a href="https://colab.research.google.com/github/kanisasthi/kavitha/blob/main/python_Fdp.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:



print (1+2)

3


In [ ]:
month=2
height=1.7
type(height)

float

In [ ]:
x="python programming"
type(x)

str

In [ ]:
y=False
type(y)

bool

In [ ]:
my_str="python rocks"
print (my_str)
print(len(my_str))
print(my_str[0])
print(my_str[-11])

python rocks
12
p
y


In [ ]:
my_str="python rocks"
print (my_str)
print(len(my_str))
print(my_str[7])
print(my_str[11
             ])

python rocks
12
r
s


In [ ]:
my_str="python rocks"
print (my_str[1])
print("y"in my_str)
print("a" in my_str)
print("rocks" in my_str)


y
True
False
True


In [ ]:
my_str="python rocks"
print(len(my_str))
print(my_str[0:3])
print(my_str[-12:])
print(my_str[:5])

12
pyt
python rocks
pytho


In [ ]:
mytup1=(12,26,-4,"python",212)
mytup2=(-21,224,27,6,"Hello",
        22)
print(mytup1)
print(len(mytup1))
print(type(mytup1))
print(mytup2)
print(len(mytup2))


(12, 26, -4, 'python', 212)
5
<class 'tuple'>
(-21, 224, 27, 6, 'Hello', 22)
6


In [ ]:
emptup=()
print(type(emptup))
print(emptup)
onetup=(212,5)
print(type(onetup))
print(onetup)

<class 'tuple'>
()
<class 'tuple'>
(212, 5)


In [ ]:
testtup1=(3,4),
testtup2=(5,6),
res=testtup1+testtup2
print("tuples are concatenation"+str(res))
print(len(res))

tuples are concatenation((3, 4), (5, 6))
2


In [ ]:
fam=["liz",343,234,43]
print(fam)


['liz', 343, 234, 43]


In [ ]:
fam=["liz",343,234,43]
type(fam)
fam


['liz', 343, 234, 43]

In [ ]:
fam=["liz",1.75,"mom",1.71,"dad",1.89]
print(fam[3:5])
fam[:4]
fam[3:]

[1.71, 'dad']


[1.71, 'dad', 1.89]

In [ ]:
fam=["liz",1.75,"mom",1.71,"dad",1.89]
(fam[3:5])
fam[:4]
fam[3:]

[1.71, 'dad', 1.89]

In [ ]:
fam=["liz",1.75,"mom",1.71,"dad",1.89]
print(fam[3:5])
print(fam[:5])
fam[2:]

[1.71, 'dad']
['liz', 1.75, 'mom', 1.71, 'dad']


['mom', 1.71, 'dad', 1.89]

In [ ]:
import numpy as np



In [ ]:
arr1=np.arry([1,2,3,4,5])
print(arr1)

AttributeError: module 'numpy' has no attribute 'arry'

In [ ]:
pip install numpy

In [ ]:
import numpy as np

In [ ]:
arr1=np.array([1,2,3,4,5])
print(arr1)

[1 2 3 4 5]


In [ ]:
arr_zeros=np.zeros((3,4))
arr_ones=np.ones((2,3))
print(arr_zeros)
print(arr_ones)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
arr2=np.arange(10)
print(arr2)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:

print(arr_zeros.size)
print(arr_zeros)
print(arr2.dtype)


12
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
int64


In [ ]:
arr3 = np.array([1, 2, 3, 4, 5,])
arr4 = np.array([10, 20, 30, 40, 50])
result_add = arr3 + arr4
print(result_add)
result_mul = arr3 * arr4
print(result_mul)



[11 22 33 44 55]
[ 10  40  90 160 250]


In [ ]:
arr5 = np.array([[1, 2, 3],
                 [4, 5, 6]])
print(arr5[0])    # Prints the first row: [1 2 3]
print(arr5[:, 1]) # Prints the second column: [2 5 8]



[1 2 3]
[2 5]


In [ ]:
arr6 = np.array([1, 2, 3, 4, 5])
print(np.sqrt(arr6))
print(np.exp(arr6))

[1.         1.41421356 1.73205081 2.         2.23606798]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


In [ ]:
import numpy as np
help(np.sqrt)

Help on ufunc:

sqrt = <ufunc 'sqrt'>
    sqrt(x, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])
    
    Return the non-negative square-root of an array, element-wise.
    
    Parameters
    ----------
    x : array_like
        The values whose square-roots are required.
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array will retain its original value.
        Note that if an uninitialized `out` array is 

In [ ]:
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
          like=None)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        ``__array__`` method returns an array, or any (nested) sequence.
        If object is a scalar, a 0-dimensional array containing object is
        returned.
    dtype : data-type, optional
        The desired data-type for the array. If not given, NumPy will try to use
        a default ``dtype`` that can represent the values (by applying promotion
        rules when necessary.)
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if ``__array__`` returns a copy, if obj is a nested
        sequence, or if a copy is needed to satisfy any of the other
        requirements (``dtype``, ``order``, e

In [ ]:
import numpy as np
a = np.array([1,2,3], dtype='int64')
print(a)
print(a.dtype)

[1 2 3]
int64


In [ ]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [ ]:
b.ndim

2

In [ ]:
a.shape

(3,)

In [ ]:
a.dtype

dtype('int64')

In [ ]:
a.itemsize

8

In [ ]:
a.nbytes

24

In [ ]:
a.size

3

In [ ]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [ ]:
a.ndim

2

In [ ]:
a[0,0]

1

In [ ]:
a[1, :]

array([ 8,  9, 10, 11, 12, 13, 14])

In [ ]:
a[:, 2]

array([ 3, 10])

In [ ]:
a[0, -1:-6:-2]

array([7, 5, 3])

In [ ]:
a[1,5] = 20

a[:,2] = [1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [ ]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
b[0,1,1]

4

In [ ]:
b[:,1,:] = [[9,9],[8,8]]

In [ ]:
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

In [ ]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [ ]:
np.full((2,3), 999)

array([[999, 999, 999],
       [999, 999, 999]])